name: ssg
description: Custom Static Site Generator for the MEGAHARD Games Website
version: 0.0.1
repository: https://github.com/MEGAHARD-Games/MEGAHARD-Games.github.io
publish_to: none

environment:
  sdk: ^3.9.2

dependencies:
  glob: ^2.1.3
  logging: ^1.3.0
  path: ^1.9.0
  techs_html_bindings:
    git:
      url: https://github.com/TechnicJelle/techs_html_bindings.git
      ref: main

dev_dependencies:
  very_good_analysis: ^10.0.0
